version: 2.1
jobs:
  build-and-test:
    working_directory: ~/repo/client
    docker:
      - image: circleci/node:12.0.0-browsers
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: krissyoshea-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: krissyoshea-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
             - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --codeCoverage=true
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
    build-and-test:
      jobs:
        - build-and-test
